call "PadSeguDPP_SET.cmd"
if not exist "PadSeguDPP_SET.cmd" call "PadSeguDPP_DEFAULT.cmd"
REG ADD "HKEY_CURRENT_USER\Software\epsxe\config" /f /v "GamepadType" /t REG_SZ /d "%PADCFG%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Stats" /t REG_DWORD /d "%P1Stats%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Joystick ID" /t REG_DWORD /d "%P1JoystickID%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Axes" /t REG_DWORD /d "%P1Axes%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Num Buttons" /t REG_DWORD /d "%P1NumButtons%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Assign" /t REG_DWORD /d "%P1Assign%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Bind Keyboard" /t REG_DWORD /d "%P1BindKeyboard%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Bind Joystick" /t REG_DWORD /d "%P1BindJoystick%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Tilt Margin" /t REG_DWORD /d "%P1TiltMargin%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P1 Enable Analog" /t REG_DWORD /d "%P1EnableAnalog%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Stats" /t REG_DWORD /d "%P2Stats%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Joystick ID" /t REG_DWORD /d "%P2JoystickID%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Axes" /t REG_DWORD /d "%P2Axes%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Num Buttons" /t REG_DWORD /d "%P2NumButtons%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Assign" /t REG_DWORD /d "%P2Assign%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Bind Keyboard" /t REG_DWORD /d "%P2BindKeyboard%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Bind Joystick" /t REG_DWORD /d "%P2BindJoystick%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Tilt Margin" /t REG_DWORD /d "%P2TiltMargin%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\PAD\Segu DPP" /f /v "P2 Enable Analog" /t REG_DWORD /d "%P2EnableAnalog%"
