call PeopsCDRASPI_SET.cmd
if not exist PeopsCDRASPI_SET.cmd call PeopsCDRASPI_DEFAULT.cmd
REG ADD "HKEY_CURRENT_USER\Software\epsxe\config" /f /v "SoundPlugin" /t REG_SZ /d "%SPUD%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "InterfaceMode" /t REG_DWORD /d "%InterfaceMode%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "Adapter" /t REG_DWORD /d "%Adapter%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "Target" /t REG_DWORD /d "%Target%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "LUN" /t REG_DWORD /d "%LUN%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "RType" /t REG_DWORD /d "%RType%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "UseCaching" /t REG_DWORD /d "%UseCaching%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "UseDataCache" /t REG_DWORD /d "%UseDataCache%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "UseSpeedLimit" /t REG_DWORD /d "%UseSpeedLimit%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "SpeedLimit" /t REG_DWORD /d "%SpeedLimit%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "NoWait" /t REG_DWORD /d "%NoWait%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "MaxRetry" /t REG_DWORD /d "%MaxRetry%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "ShowReadErr" /t REG_DWORD /d "%ShowReadErr%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "UsePPF" /t REG_DWORD /d "%UsePPF%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "UseSubReading" /t REG_DWORD /d "%UseSubReading%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "PPFFile" /t REG_DWORD /d "%PPFFile%"
reg add "HKCU\Software\Vision Thing\PSEmu Pro\CDR\PeopsCDRASPI" /f /v "SCFile" /t REG_DWORD /d "%SCFile%"