for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_up"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_up=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_down"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_down=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_left"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_left=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_right"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_right=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_c"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_c=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_b"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_b=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_a"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_a=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_option"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_option=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_pause"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_pause=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_0"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_0=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_1"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_1=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_2"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_2=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_3"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_3=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_4"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_4=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_5"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_5=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_6"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_6=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_7"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_7=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_8"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_8=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_9"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_9=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_pound"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_pound=%%~a>>P2_SET.cmd
for /f "tokens=3 delims= " %%a in ('reg query "HKCU\Software\Underground Software\Virtual Jaguar" /v "p1k_star"') do if "%%~a" NEQ "Jaguar" echo.SET p1k_star=%%~a>>P2_SET.cmd